M48
; DRILL file {KiCad (6.0.1)} date Wed Feb  2 16:17:23 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-02T16:17:23-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.11Y-4.16
T2
X5.8Y-3.8
X5.8Y-3.9
X5.8Y-4.0
X5.8Y-4.1
X5.8Y-4.2
X5.8Y-4.3
X6.2Y-3.8
X6.2Y-3.9
X6.2Y-4.2
X6.2Y-4.3
T0
M30
